// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShopProject.Api.Data;

#nullable disable

namespace ProductDataApi.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductDataApi.Data.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("productType")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            datetime = new DateTime(2024, 11, 1, 21, 32, 26, 746, DateTimeKind.Local).AddTicks(4125),
                            description = "cdcd",
                            name = "P1",
                            price = 300m,
                            productType = 1
                        },
                        new
                        {
                            id = 2,
                            datetime = new DateTime(2024, 11, 1, 21, 32, 26, 746, DateTimeKind.Local).AddTicks(4142),
                            description = "cdcdsef",
                            name = "P2",
                            price = 400m,
                            productType = 0
                        },
                        new
                        {
                            id = 3,
                            datetime = new DateTime(2024, 11, 1, 21, 32, 26, 746, DateTimeKind.Local).AddTicks(4143),
                            description = "cdfcd",
                            name = "P3",
                            price = 500m,
                            productType = 2
                        },
                        new
                        {
                            id = 4,
                            datetime = new DateTime(2024, 11, 1, 21, 32, 26, 746, DateTimeKind.Local).AddTicks(4145),
                            description = "cdsfsfcd",
                            name = "P4",
                            price = 600m,
                            productType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
